version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - zaprove-network

  core-service:
    build: ./core
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - zaprove-network

  disbursement-service:
    build: ./disbursement-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - zaprove-network

  notification-service:
    build: ./notification-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - zaprove-network

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:80"
  #   networks:
  #     - zaprove-network

networks:
  zaprove-network:
    driver: bridge