version: '3.8'

services:
  core-service:
    build: ./core
    ports:
      - "8081:8081"
    networks:
      - zaprove-network

  disbursement-service:
    build: ./disbursement-service
    ports:
      - "8083:8083"
    networks:
      - zaprove-network

  notification-service:
    build: ./notification-service
    ports:
      - "8082:8082"
    networks:
      - zaprove-network

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:80"
  #   networks:
  #     - zaprove-network

networks:
  zaprove-network:
    driver: bridge
