global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'core-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['core-service:8080']
  - job_name: 'disbursement-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['disbursement-service:8081']
  - job_name: 'notification-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['notification-service:8082']
  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eureka-server:8761']
