# logstash.conf

input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["audit.events"]
    codec => "json"
    group_id => "logstash_audit_consumer"
  }
}

filter {
  # At this stage, the JSON from our Spring Boot app is already well-structured.
  # We could add more filters here later, like geoip for an IP address.
  # For now, we just let the data pass through.
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "audit-logs-%{+YYYY.MM.dd}"
  }
  # For debugging purposes, we can also print events to the console.
  stdout {
    codec => rubydebug
  }
}
